### ISSUE TITLE
Terraform Provider Development Program

### ISSUE THREAD

**Issue by cgriggs01** [vancluever/terraform-provider-acme-old#65]
Hey Chris 👋 

I went through the repo and found a few items we should address before merging the provider into terraform-repostories/ org.  

- [ ] Is the 'doc' directory necessary, looks like its just the doc pages for the provider's resources. Can it be removed?

- [ ] Do you plan on create a examples/ dir with example terraform configs?

- [ ] The repo currently have a Apache license, the standard for all Terraform providers is a MPL2 license, could you update that?

- [ ] The Makefile is not aligned with the standard GNUmakefile used across Terraform provider. You'll need to make sure that the tasks in your makefile align the standard tasks. 

We can talk more about this tomorrow. :)

**Comment by vancluever** [comment]
Hey @cgriggs01, as discussed:

* We will remove `doc` on duplication
* No examples for now. However the docs have good examples that people should be able to copy/paste from. Anyone so enterprising could make some modules for the registry. :slightly_smiling_face: 
* I'll re-license MPL when we duplicate.
* I'll work on rotating in the proper template `Makefile` shortly.

**Comment by vancluever** [comment]
Closing this out as we working on all of this currently.
